FROM mcr.microsoft.com/mssql/server:2019-latest

ARG ARG_PASSWORD

ENV SA_PASSWORD=$ARG_PASSWORD
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Enterprise

EXPOSE 1433/tcp

VOLUME ./volumes/microsoft:/var/opt/mssql/data

